# Generated by Django 5.0 on 2024-01-29 12:03

import django.contrib.auth.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_contact_phone_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('customer', 'customer'), ('partner', 'partner')], default='customer', max_length=8),
        ),
        migrations.AlterField(
            model_name='address',
            name='contact',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='backend.contact'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, max_length=200, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()]),
        ),
    ]
